### ISSUE TITLE
可以在README里提供一个简单的codepen或codesandbox的在线演示吗

### ISSUE THREAD

**Issue by CNFeffery** [yuanguandong/react-dashboard-pro#3]
如题

**Comment by yuanguandong** [comment]
可以，我抽空搞一个

**Comment by CNFeffery** [comment]
> 可以，我抽空搞一个

感谢回复，期待😀

**Comment by yuanguandong** [comment]
> > 可以，我抽空搞一个
> 
> 感谢回复，期待😀

codesandbox在线demo弄好了

[![alt text](https://codesandbox.io/static/img/play-codesandbox.svg "在线编辑")](https://codesandbox.io/s/react-dashboard-pro-demo-6doss?file=/src/App.tsx)

**Comment by CNFeffery** [comment]
> > > 可以，我抽空搞一个
> > 
> > 
> > 感谢回复，期待😀
> 
> codesandbox在线demo弄好了
> 
> [![alt text](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/react-dashboard-pro-demo-6doss?file=/src/App.tsx)

非常感谢👍
